var orarClaseleGimnaziale = [
  {
    clasa: "V-a",
    nrElevi: 28,
    imagineDiriginte: "./img/img_msg/parinte_3.png",
    numeDiriginte: "Pascari Raisa",
    orar: {
      Luni: [
        "Stiinta",
        "Matematica",
        "Limba Romana",
        "Limba Romana",
        "Dezvoltare Personala",
        "Limba Engleza",
      ],
      Marti: [
        "Limba Romana",
        "Limba Romana",
        "Istoria",
        "Matematica",
        "Limba Franceza",
        "Educatia Tehnologica",
      ],
      Miercuri: [
        "Matematica",
        "Matematica",
        "Limba Romana",
        "Limba Franceza",
        "Educatia Fizica",
        "Limba Romana",
      ],
      Joi: [
        "Limba Romana",
        "Limba Engleza",
        "Stiinta",
        "Educatia Tehnologica",
        "Educatia Plastica",
      ],
      Vineri: [
        "Geografia",
        "Educatia Fizica",
        "Matematica",
        "Educatia Muzicala",
      ],
    }, // end orar
  }, // end clasa V-a
  {
    clasa: "VI-a",
    nrElevi: 20,
    imagineDiriginte: "./img/img_msg/parinte_4.png",
    numeDiriginte: "Pascari Raisa",
    orar: {
      Luni: [
        "Limba Romana",
        "Limba Romana",
        "Matematica",
        "Biologie",
        "Limba Engleza",
        "Educatia Plastica",
      ],
      Marti: [
        "Matematica",
        "Limba Romana",
        "Istoria",
        "Educatia pentru Societate",
        "Limba Engleza",
        "Educatia Tehnologica",
      ],
      Miercuri: [
        "Limba Romana",
        "Limba Romana",
        "Dezvoltarea Personala",
        "Limba Engleza",
        "Biologie",
      ],
      Joi: [
        "Limba Romana",
        "Limba Engleza",
        "Matematica",
        "Limba Romana",
        "Matematica",
        "Educatia Fizica",
      ],
      Vineri: [
        "Geografia",
        "Limba Franceza",
        "Educatia Fizica",
        "Informatica",
        "Educatia Muzicala",
      ],
    }, // end orar
  }, // end clasa I-b
  {
    clasa: "VII-a",
    nrElevi: 17,
    imagineDiriginte: "./img/img_msg/parinte_5.png",
    numeDiriginte: "Pascari Raisa",
    orar: {
      Luni: [
        "Biologie",
        "Chimie",
        "Limba Franceza",
        "Matematica",
        "Istoria",
        "Educatia Tehnologica",
        "Educatia Plastica",
      ],
      Marti: [
        "Fizica",
        "Educatie Fizica",
        "Limba Romana",
        "Limba Romana",
        "Istoria",
        "Educatia pentru Societate",
      ],
      Miercuri: [
        "Limba Romana",
        "Limba Romana",
        "Matematica",
        "Limba Engleza",
        "Dezvoltare Personala",
        "Biologie",
      ],
      Joi: [
        "Matematica",
        "Limba Engleza",
        "Limba Romana",
        "Matematica",
        "Informatica",
      ],
      Vineri: [
        "Fizica",
        "Educatia Fizica",
        "Geografia",
        "Limba Franceza",
        "Educatia Muzicala",
        "Programare Web",
      ],
    }, // end orar
  }, // end clasa I-b
  {
    clasa: "VIII-a",
    nrElevi: 20,
    imagineDiriginte: "./img/img_msg/parinte_6.png",
    numeDiriginte: "Pascari Raisa",
    orar: {
      Luni: [
        "Dezvoltarea Personala",
        "Matematica",
        "Limba Romana",
        "Limba Romana",
        "Matematica",
        "Limba Engleza",
        "Educatia Tehnologica",
      ],
      Marti: [
        "Matematica",
        "Limba Romana",
        "Limba Romana",
        "Matematica",
        "Limba Engleza",
        "Dezvoltarea Personala",
        "Educatia Tehnologica",
      ],
      Miercuri: [
        "Limba Romana",
        "Limba Romana",
        "Dezvoltarea Personala",
        "Matematica",
        "Matematica",
        "Limba Engleza",
        "Educatia Tehnologica",
      ],
      Joi: [
        "Limba Romana",
        "Limba Engleza",
        "Dezvoltarea Personala",
        "Matematica",
        "Matematica",
        "Educatia Tehnologica",
        "Limba Romana",
      ],
      Vineri: [
        "Dezvoltarea Personala",
        "Limba Romana",
        "Matematica",
        "Limba Romana",
        "Limba Engleza",
        "Educatia Tehnologica",
        "Matematica",
      ],
    }, // end orar
  }, // end clasa I-b
  {
    clasa: "IX-a",
    nrElevi: 20,
    imagineDiriginte: "./img/img_msg/parinte_6.png",
    numeDiriginte: "Pascari Raisa",
    orar: {
      Luni: [
        "Dezvoltarea Personala",
        "Matematica",
        "Limba Romana",
        "Limba Romana",
        "Matematica",
        "Limba Engleza",
        "Educatia Tehnologica",
      ],
      Marti: [
        "Matematica",
        "Limba Romana",
        "Limba Romana",
        "Matematica",
        "Limba Engleza",
        "Dezvoltarea Personala",
        "Educatia Tehnologica",
      ],
      Miercuri: [
        "Limba Romana",
        "Limba Romana",
        "Dezvoltarea Personala",
        "Matematica",
        "Matematica",
        "Limba Engleza",
        "Educatia Tehnologica",
      ],
      Joi: [
        "Limba Romana",
        "Limba Engleza",
        "Dezvoltarea Personala",
        "Matematica",
        "Matematica",
        "Educatia Tehnologica",
        "Limba Romana",
      ],
      Vineri: [
        "Dezvoltarea Personala",
        "Limba Romana",
        "Matematica",
        "Limba Romana",
        "Limba Engleza",
        "Educatia Tehnologica",
        "Matematica",
      ],
    }, // end orar
  }, // end clasa I-b
];
